### ISSUE TITLE
Does enm support zero-copy IPC?

### ISSUE THREAD

**Issue by osense** [basho/enm#13]
Hello,

this is more of a question than an issue. I'm guessing that the answer is no, as there is no mention of zero-copy anywhere in this repo as far as I can see. I understand that zero-copy is hard (or even impossible) to do in languages with GC, but I don't know enough about the inner workings of the BEAM to judge whether it is possible here or not.

Thanks

**Comment by vinoski** [comment]
Your question assumes nanomsg itself is zero-copy; I don't believe it is, which implies `enm` can't be either. The `enm` wrapper avoids copying whenever it can but copies are sometimes unavoidable, such as when data must be queued when a send is attempted on a socket that's unwritable due to flow control, or for reads when the current buffer isn't large enough to hold the incoming data and so a new binary is allocated and the data copied into it.

**Comment by osense** [comment]
nanomsg *aims* to be zero copy, whether it is so in the current
implementation I do not know, however there is an example of sending a
message from C in a zero-copy fashion [1], and also the document
outlying the differences between ZeroMQ and namomsg says

> While ZeroMQ offers a "zero-copy" API, it's not true zero-copy. Rather
> it's "zero-copy till the message gets to the kernel boundary". From
> that point on data is copied as with standard TCP. nanomsg, on the
> other hand, aims at supporting true zero-copy mechanisms such as RDMA
> (CPU bypass, direct memory-to-memory copying) and shmem (transfer of
> data between processes on the same box by using shared memory). The
> API entry points for zero-copy messaging are nn_allocmsg and
> nn_freemsg functions in combination with NN_MSG option passed to
> send/recv functions.

Anyway, thanks for the quick reply, it is good to at least know that
copying doesn't have to occur for each time you send/receive a message."


[1]
https://github.com/nanomsg/nanomsg/blob/42977e00776b4fea279d6311fb9756d132fa952c/doc/nn_allocmsg.txt
