### ISSUE TITLE
How to use rep for multiple worker?

### ISSUE THREAD

**Issue by johnzeng** [basho/enm#20]
Hi, I have to draw my cluster picture here at first:

- I have a master server using enm, who has a `rep` socket opened on `hostname:9010`
- I have several stateless workers using enm, each of them has a `req` socket connected to the master server.

The Rep socket is created like this:

```
 enm:rep([{bind, Url}, {nodelay, true}])
```

My resposne codes are like this:

```
handle_info({nnrep, Sock, Data}, #state{sock = Sock, handler = Handler} = State) ->
  lager:debug("receive a nnrep: ~p ~p", [self(), Sock]),
  Handler ! {notify_req, {self(), Data}},
  %% send response for this request.
  send_data(Sock, <<"ok">>),
  {noreply, State};
```

The req client is created like this:

```
enm:req([{connect, Url}, {nodelay, true}])
```

The request codes are like this:
```
handle_call({request, ReqData}, _From, #state{sock = Sock} = State) ->
  %% send a request from req socket
  case enm:send(Sock, ReqData) of
    ok ->
      %% send ok, now wait for response
      receive
        {nnreq, Sock, Data} ->
           %% reply is received, return {ok, data}
          {reply, {ok, Data}, State}
      after
        ?RPC_TIMEOUT ->
          lager:error("wait reply timeout"),
          {reply, {error, timeout}, State}
      end;
    Else ->
      {reply, Else, State}
  end;

```

If the request number from workers is large, the `rep` socket will be closed by `efsm`.

As I read from #15 , looks like if I send multiple rep to a single req, the statemachine will crash, but I don't know how to send the rep to a special worker because the notify from enm is `{nnrep, Sock, Data}`, and `Sock` is the socket of `rep`, so I don't think that sending data to this sock will be response to the special worker when there are multiple workers connecting to this socket.

Am I using the req/rep protocol in the wrong way?
**How can I send rep correctly if I have multiple req clients?**
I need a rpc server to response the message from workers, how should I do?

BTW, nanomsg already release 1.0 version lib, do you mind to upgrade to it?

**Comment by vinoski** [comment]
First let me answer your final question: nanomsg 1.0 is not a simple upgrade from 0.8, so it's unlikely that switching to 1.0 will occur anytime soon, if ever.

The `Sock` in `{nnrep, Sock, Data}` is not a socket but an Erlang port, which is essentially an opaque object the Erlang driver in enm uses to encapsulate the underlying nanomsg sockets. If you look at the `enm_reqrep.erl` test in enm, you can see that it has two reqs communicating with a single rep, and it works correctly. As an experiment, I also just ran three interactive Erlang shells, starting a rep in one and reqs in the other two, and requests and replies were received correctly by each endpoint as expected.

If you use TCP, try binding a rep, then connecting two reqs, and then using `lsof` or equivalent on the `beam.smp` OS process running the rep. Part of what you see in the output from `lsof` will look like this (I've dropped some of the output columns to focus on the important parts):

    beam.smp 5265 41u IPv4 TCP localhost:51000->localhost:52001 (ESTABLISHED)
    beam.smp 5265 42u IPv4 TCP localhost:51000->localhost:52015 (ESTABLISHED)

Here, we see two connections, one for each req. The output includes the executable name `beam.smp`, the OS process id 5265, the file descriptor numbers for the connections, and the TCP/IP details including interfaces and port numbers. As the output shows, each client has its own port, and therefore each connection is unique because it comprises both the server and the client endpoint details, and this is how replies get to the right clients.

Regarding your statement that a large number of reqs causes the rep to die with `efsm`, as you saying that's a problem with your application, or a problem with enm? If the latter, can you supply a small test case to show the problem?

**Comment by johnzeng** [comment]
Hi, thanks for your quick response. I believe this issue is from nanomsg c lib, not enm. The only thing I can do to fix it is that I just send request from `req` to `rep`, and never reply from `rep` . 

Refer to `nanomsg/src/protocols/rep.c` , just care about the `rep->falgs` in:

```c
int nn_rep_send (struct nn_sockbase *self, struct nn_msg *msg)
{
    int rc;
    struct nn_rep *rep;

    rep = nn_cont (self, struct nn_rep, xrep.sockbase);

    /*  If no request was received, there's nowhere to send the reply to. */
    if (nn_slow (!(rep->flags & NN_REP_INPROGRESS)))
        return -EFSM;

    /*  Move the stored backtrace into the message header. */
    nn_assert (nn_chunkref_size (&msg->sphdr) == 0);
    nn_chunkref_term (&msg->sphdr);
    nn_chunkref_mv (&msg->sphdr, &rep->backtrace);
    rep->flags &= ~NN_REP_INPROGRESS;

    /*  Send the reply. If it cannot be sent because of pushback,
        drop it silently. */
    rc = nn_xrep_send (&rep->xrep.sockbase, msg);
    errnum_assert (rc == 0 || rc == -EAGAIN, -rc);

    return 0;
}

int nn_rep_recv (struct nn_sockbase *self, struct nn_msg *msg)
{
    int rc;
    struct nn_rep *rep;

    rep = nn_cont (self, struct nn_rep, xrep.sockbase);

    /*  If a request is already being processed, cancel it. */
    if (nn_slow (rep->flags & NN_REP_INPROGRESS)) {
        nn_chunkref_term (&rep->backtrace);
        rep->flags &= ~NN_REP_INPROGRESS;
    }

    /*  Receive the request. */
    rc = nn_xrep_recv (&rep->xrep.sockbase, msg);
    if (nn_slow (rc == -EAGAIN))
        return -EAGAIN;
    errnum_assert (rc == 0, -rc);

    /*  Store the backtrace. */
    nn_chunkref_mv (&rep->backtrace, &msg->sphdr);
    nn_chunkref_init (&msg->sphdr, 0);
    rep->flags |= NN_REP_INPROGRESS;

    return 0;
}
```

The flag is overrided by [~]NN_REP_INPROGRESS everytime you call the recv or send on a rep sock, it never backup the state, so I think if any client do multiple requests at the same time and doesn't wait for a response, this code will return efsm( I haven't reviewed all the coes yet, so let me know if I make any mistake). Also if there are two clients sending tons of msgs at the same time, and the rep socket happen to reveive two msgs from two clients before responsing any of them, the `rep` socket will return efsm as well.

Also I have an example for the error:

```
-module(server).

-export([start/0]).
start() ->
    process_flag(trap_exit, true),
    case enm:rep([{bind, "tcp://127.0.0.1:7011"}, {nodelay, true}]) of
        {ok, Sock} ->
            handle_msg();
        ELSE ->
            io:format("open socket failed:~p", [ELSE])
    end.

handle_msg()->
    receive 
        {nnrep, Sock, Data} ->
            timer:sleep(100),
            enm:send(Sock, <<"ok">>),
            handle_msg();
        Else ->
            io:format("other msg recv: ~p", [Else])
    end.
```

```
-module(client).

-export([start/0]).

start() ->
    case enm:req([{connect, "tcp://127.0.0.1:7011"}, {nodelay, true}]) of
        {ok, Sock} ->
            do_req(Sock);
        ELSE ->
            io:format("open req failed")
    end.

do_req(Sock) ->
    do_request(100000, Sock),
    do_receive(100000),
    timer:sleep(100),
    do_req(Sock).

do_request(0, Sock) ->
    ok;
do_request(Counter, Sock) ->
    spawn(fun() -> enm:send(Sock, integer_to_binary(Counter)) end),
    do_request(Counter - 1, Sock).

do_receive(0) ->
    ok;
do_receive(Counter) ->
    receive
        {nnreq, Sock, Data} ->
            do_receive(Counter - 1);
        _ ->
            io:format("fail in middle", []),
            ok
    end.
```

I think this should not be a issue of enm, so I am closing this issue.

Still, thanks for your replying.

**Comment by vinoski** [comment]
As you probably know, the problem with your example is that you have a bunch of individual req endpoints all using the same socket to communicate with the same rep. They all send requests without awaiting replies, triggering the `efsm` error from nanomsg.

To avoid this you can either use a state machine on the req side to control the req socket so that it maintains request/reply ordering at all times, or you can fire up a whole bunch of separate Erlang req processes in your client, each with its own socket. The cost of the first approach is that you have a bunch of Erlang request processes all sending their requests through the state machine; all those requests get multiplexed over a single socket, so depending on how many requests they send, your client processes might end up waiting around quite a bit for other requests to be serviced first. The cost of the second approach is that each client ends up with its own TCP connection to the server, but on modern hardware that's not a problem.

Here are modified versions of your server and client code that take the second approach. First, the server:

    -module(server).
    -export([start/0]).

    start() ->
        enm:start(),
        case enm:rep([{bind, "tcp://*:7011"}, {nodelay, true}]) of
            {ok, Sock} ->
                handle_msg(Sock);
            Else ->
                io:format("open socket failed: ~p\n", [Else])
        end.

    handle_msg(Sock)->
        receive
            {nnrep, Sock, <<"close">>} ->
                enm:close(Sock);
            {nnrep, Sock, Data} ->
                ok = enm:send(Sock, Data),
                handle_msg(Sock);
            Else ->
                io:format("other msg recv: ~p\n", [Else])
        end.

As you can see, the server replies with the same data sent to it. For the req side, the code below creates 10000 clients. It associates a numeric value with each req process, and that value is what each req client sends in its request and expects in its response.

    -module(client).
    -export([start/0]).

    start() ->
        enm:start(),
        ok = do_req(10000).

    do_req(0) ->
        ok;
    do_req(Count) ->
        spawn(fun() -> do_request(Count) end),
        do_req(Count - 1).

    do_request(Num) ->
        case enm:req([{connect, "tcp://localhost:7011"}, {nodelay, true}]) of
            {ok, Sock} ->
                Data = integer_to_binary(Num),
                ok = enm:send(Sock, Data),
                receive
                    {nnreq, Sock, Data} when Num == 1 ->
                        ok = enm:send(Sock, <<"close">>),
                        ok;
                    {nnreq, Sock, Data} ->
                        ok;
                    Fail ->
                        io:format("client ~w failed: ~p\n", [Num, Fail]),
                        Fail
                end,
                enm:close(Sock);
            Else ->
                io:format("client ~w req failed: ~p\n", [Num, Else])
        end.

Also note that the client with the final number, 1, sends a `<<"close">>` message to the server, which the server watches for so it can stop cleanly. I added this just to make them easier to use interactively in the Erlang shell.

**Comment by johnzeng** [comment]
@vinoski bad news, your codes ends up with `client req failed:  {error,emfile}`  , good news, the server was not crashed.... Do you mean the server have to handle all requests one by one? And the clients have to send request one by one, too? I am running Erlang 16B on ubunut12, as I read from the Erlang's document:

```

**Comment by vinoski** [comment]
Yes, with the reqrep protocol, the server has to handle a request, then send a reply.

Another alternative, if you're not tied to using reqrep, might be to use the [pair protocol](http://nanomsg.org/v0.8/nn_pair.7.html) instead, as then client and server have no such ordering constraints. You could have any number of Erlang processes on the client side sending requests on the same socket, and the server can receive and handle them in any order it wishes. But note that if the client socket is in an [active mode](https://github.com/basho/enm#socket-options) (`true` (the default), `once`, or `N`), all replies will go to the controlling Erlang process for the socket regardless of which Erlang process sent the request. The controlling process is normally the process that opens the socket, but it can be changed via `enm:controlling_process/2`. This means that requests should include some kind of identifier that the controlling process can use to direct each response to the process that sent it.

(BTW if you get `{error, emfile}` it's because you've hit the OS limit for the maximum number of open files each process can have on your host. You can check this and change it with `ulimit -n`.)

**Comment by johnzeng** [comment]
@vinoski yes, I get that. Anyway, I am moving to other rpc frameworks, as my company is using erlang for most of our modules, I just go back to erlang rpc module....

**Comment by vinoski** [comment]
Fair enough. Just be aware that the Erlang rpc `rex` process receives all incoming requests per node, independent of the server application to which the requests are ultimately directed, and so it can easily be a bottleneck. There's no free lunch. Have a look at ["Investigating the Scalability Limits of Distributed Erlang"](http://www.dcs.gla.ac.uk/~amirg/publications/DE-Bench.pdf) if you're interested in more details, and (shameless plug ahead) there's [*Designing for Scalability with Erlang/OTP*](http://shop.oreilly.com/product/0636920024149.do) as well.

**Comment by johnzeng** [comment]
great thanks for your advices:)
